/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: testapi@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * FIAttributionForSecurities
 */
@JsonPropertyOrder({
  FIAttributionForSecurities.JSON_PROPERTY_START_PRICE,
  FIAttributionForSecurities.JSON_PROPERTY_END_PRICE,
  FIAttributionForSecurities.JSON_PROPERTY_START_SPREAD,
  FIAttributionForSecurities.JSON_PROPERTY_END_SPREAD,
  FIAttributionForSecurities.JSON_PROPERTY_PRICING_METHOD
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class FIAttributionForSecurities implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_START_PRICE = "startPrice";
  private Double startPrice;

  public static final String JSON_PROPERTY_END_PRICE = "endPrice";
  private Double endPrice;

  public static final String JSON_PROPERTY_START_SPREAD = "startSpread";
  private Double startSpread;

  public static final String JSON_PROPERTY_END_SPREAD = "endSpread";
  private Double endSpread;

  /**
   * Pricing Method
   */
  public enum PricingMethodEnum {
    INPUTTED_PRICE("Inputted Price"),
    
    PRICING_MATRIX("Pricing Matrix"),
    
    ACTUAL_SPREAD("Actual Spread"),
    
    OAS("OAS");

    private String value;

    PricingMethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PricingMethodEnum fromValue(String value) {
      for (PricingMethodEnum b : PricingMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PRICING_METHOD = "pricingMethod";
  private PricingMethodEnum pricingMethod;


  public FIAttributionForSecurities startPrice(Double startPrice) {
    this.startPrice = startPrice;
    return this;
  }

   /**
   * Start Price
   * @return startPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Start Price")
  @JsonProperty(JSON_PROPERTY_START_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getStartPrice() {
    return startPrice;
  }


  public void setStartPrice(Double startPrice) {
    this.startPrice = startPrice;
  }


  public FIAttributionForSecurities endPrice(Double endPrice) {
    this.endPrice = endPrice;
    return this;
  }

   /**
   * End Price
   * @return endPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "End Price")
  @JsonProperty(JSON_PROPERTY_END_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getEndPrice() {
    return endPrice;
  }


  public void setEndPrice(Double endPrice) {
    this.endPrice = endPrice;
  }


  public FIAttributionForSecurities startSpread(Double startSpread) {
    this.startSpread = startSpread;
    return this;
  }

   /**
   * Start Spread
   * @return startSpread
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Start Spread")
  @JsonProperty(JSON_PROPERTY_START_SPREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getStartSpread() {
    return startSpread;
  }


  public void setStartSpread(Double startSpread) {
    this.startSpread = startSpread;
  }


  public FIAttributionForSecurities endSpread(Double endSpread) {
    this.endSpread = endSpread;
    return this;
  }

   /**
   * End Spread
   * @return endSpread
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "End Spread")
  @JsonProperty(JSON_PROPERTY_END_SPREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getEndSpread() {
    return endSpread;
  }


  public void setEndSpread(Double endSpread) {
    this.endSpread = endSpread;
  }


  public FIAttributionForSecurities pricingMethod(PricingMethodEnum pricingMethod) {
    this.pricingMethod = pricingMethod;
    return this;
  }

   /**
   * Pricing Method
   * @return pricingMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Pricing Method")
  @JsonProperty(JSON_PROPERTY_PRICING_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PricingMethodEnum getPricingMethod() {
    return pricingMethod;
  }


  public void setPricingMethod(PricingMethodEnum pricingMethod) {
    this.pricingMethod = pricingMethod;
  }


  /**
   * Return true if this FIAttributionForSecurities object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FIAttributionForSecurities fiAttributionForSecurities = (FIAttributionForSecurities) o;
    return Objects.equals(this.startPrice, fiAttributionForSecurities.startPrice) &&
        Objects.equals(this.endPrice, fiAttributionForSecurities.endPrice) &&
        Objects.equals(this.startSpread, fiAttributionForSecurities.startSpread) &&
        Objects.equals(this.endSpread, fiAttributionForSecurities.endSpread) &&
        Objects.equals(this.pricingMethod, fiAttributionForSecurities.pricingMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startPrice, endPrice, startSpread, endSpread, pricingMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FIAttributionForSecurities {\n");
    sb.append("    startPrice: ").append(toIndentedString(startPrice)).append("\n");
    sb.append("    endPrice: ").append(toIndentedString(endPrice)).append("\n");
    sb.append("    startSpread: ").append(toIndentedString(startSpread)).append("\n");
    sb.append("    endSpread: ").append(toIndentedString(endSpread)).append("\n");
    sb.append("    pricingMethod: ").append(toIndentedString(pricingMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

