/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * FIJobSettings
 */
@JsonPropertyOrder({
  FIJobSettings.JSON_PROPERTY_YIELD_CURVE_DATE,
  FIJobSettings.JSON_PROPERTY_PARTIAL_DURATION_MONTHS
})

public class FIJobSettings implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_YIELD_CURVE_DATE = "yieldCurveDate";
  private String yieldCurveDate;

  public static final String JSON_PROPERTY_PARTIAL_DURATION_MONTHS = "partialDurationMonths";
  private java.util.List<Integer> partialDurationMonths = null;


  public FIJobSettings yieldCurveDate(String yieldCurveDate) {
    
    this.yieldCurveDate = yieldCurveDate;
    return this;
  }

   /**
   * Get yieldCurveDate
   * @return yieldCurveDate
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_YIELD_CURVE_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getYieldCurveDate() {
    return yieldCurveDate;
  }


  public void setYieldCurveDate(String yieldCurveDate) {
    this.yieldCurveDate = yieldCurveDate;
  }


  public FIJobSettings partialDurationMonths(java.util.List<Integer> partialDurationMonths) {
    
    this.partialDurationMonths = partialDurationMonths;
    return this;
  }

  public FIJobSettings addPartialDurationMonthsItem(Integer partialDurationMonthsItem) {
    if (this.partialDurationMonths == null) {
      this.partialDurationMonths = new java.util.ArrayList<Integer>();
    }
    this.partialDurationMonths.add(partialDurationMonthsItem);
    return this;
  }

   /**
   * Get partialDurationMonths
   * @return partialDurationMonths
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PARTIAL_DURATION_MONTHS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.List<Integer> getPartialDurationMonths() {
    return partialDurationMonths;
  }


  public void setPartialDurationMonths(java.util.List<Integer> partialDurationMonths) {
    this.partialDurationMonths = partialDurationMonths;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FIJobSettings fiJobSettings = (FIJobSettings) o;
    return Objects.equals(this.yieldCurveDate, fiJobSettings.yieldCurveDate) &&
        Objects.equals(this.partialDurationMonths, fiJobSettings.partialDurationMonths);
  }

  @Override
  public int hashCode() {
    return Objects.hash(yieldCurveDate, partialDurationMonths);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FIJobSettings {\n");
    sb.append("    yieldCurveDate: ").append(toIndentedString(yieldCurveDate)).append("\n");
    sb.append("    partialDurationMonths: ").append(toIndentedString(partialDurationMonths)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

