/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * OptimalPortfolio
 */
@JsonPropertyOrder({
  OptimalPortfolio.JSON_PROPERTY_ACCTNAME,
  OptimalPortfolio.JSON_PROPERTY_EXCLUDEZERO,
  OptimalPortfolio.JSON_PROPERTY_ARCHIVEDATE,
  OptimalPortfolio.JSON_PROPERTY_IFEXISTS
})

public class OptimalPortfolio implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACCTNAME = "acctname";
  private String acctname;

  public static final String JSON_PROPERTY_EXCLUDEZERO = "excludezero";
  private Boolean excludezero;

  public static final String JSON_PROPERTY_ARCHIVEDATE = "archivedate";
  private String archivedate;

  /**
   * Archive action if account exists
   */
  public enum IfexistsEnum {
    OVERWRITE("Overwrite"),
    
    APPENDDATE("Appenddate"),
    
    FAIL("Fail");

    private String value;

    IfexistsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IfexistsEnum fromValue(String value) {
      for (IfexistsEnum b : IfexistsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_IFEXISTS = "ifexists";
  private IfexistsEnum ifexists;


  public OptimalPortfolio acctname(String acctname) {
    
    this.acctname = acctname;
    return this;
  }

   /**
   * Account path
   * @return acctname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Account path")
  @JsonProperty(JSON_PROPERTY_ACCTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAcctname() {
    return acctname;
  }


  public void setAcctname(String acctname) {
    this.acctname = acctname;
  }


  public OptimalPortfolio excludezero(Boolean excludezero) {
    
    this.excludezero = excludezero;
    return this;
  }

   /**
   * Exclude zero
   * @return excludezero
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Exclude zero")
  @JsonProperty(JSON_PROPERTY_EXCLUDEZERO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getExcludezero() {
    return excludezero;
  }


  public void setExcludezero(Boolean excludezero) {
    this.excludezero = excludezero;
  }


  public OptimalPortfolio archivedate(String archivedate) {
    
    this.archivedate = archivedate;
    return this;
  }

   /**
   * Archive date
   * @return archivedate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Archive date")
  @JsonProperty(JSON_PROPERTY_ARCHIVEDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArchivedate() {
    return archivedate;
  }


  public void setArchivedate(String archivedate) {
    this.archivedate = archivedate;
  }


  public OptimalPortfolio ifexists(IfexistsEnum ifexists) {
    
    this.ifexists = ifexists;
    return this;
  }

   /**
   * Archive action if account exists
   * @return ifexists
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Archive action if account exists")
  @JsonProperty(JSON_PROPERTY_IFEXISTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IfexistsEnum getIfexists() {
    return ifexists;
  }


  public void setIfexists(IfexistsEnum ifexists) {
    this.ifexists = ifexists;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OptimalPortfolio optimalPortfolio = (OptimalPortfolio) o;
    return Objects.equals(this.acctname, optimalPortfolio.acctname) &&
        Objects.equals(this.excludezero, optimalPortfolio.excludezero) &&
        Objects.equals(this.archivedate, optimalPortfolio.archivedate) &&
        Objects.equals(this.ifexists, optimalPortfolio.ifexists);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acctname, excludezero, archivedate, ifexists);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OptimalPortfolio {\n");
    sb.append("    acctname: ").append(toIndentedString(acctname)).append("\n");
    sb.append("    excludezero: ").append(toIndentedString(excludezero)).append("\n");
    sb.append("    archivedate: ").append(toIndentedString(archivedate)).append("\n");
    sb.append("    ifexists: ").append(toIndentedString(ifexists)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

