/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v2:[pa,spar,vault,pub],v1:[fiab,fi,axp,afi,npo,bpm,fpo]
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import factset.analyticsapi.engines.models.OptimalHoldings;
import factset.analyticsapi.engines.models.OptimalPortfolio;
import factset.analyticsapi.engines.models.TradesList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * OutputTypes
 */
@JsonPropertyOrder({
  OutputTypes.JSON_PROPERTY_TRADES,
  OutputTypes.JSON_PROPERTY_OPTIMAL,
  OutputTypes.JSON_PROPERTY_ACCOUNT
})

public class OutputTypes implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_TRADES = "trades";
  private TradesList trades;

  public static final String JSON_PROPERTY_OPTIMAL = "optimal";
  private OptimalHoldings optimal;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  private OptimalPortfolio account;


  public OutputTypes trades(TradesList trades) {
    
    this.trades = trades;
    return this;
  }

   /**
   * Get trades
   * @return trades
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TRADES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TradesList getTrades() {
    return trades;
  }


  public void setTrades(TradesList trades) {
    this.trades = trades;
  }


  public OutputTypes optimal(OptimalHoldings optimal) {
    
    this.optimal = optimal;
    return this;
  }

   /**
   * Get optimal
   * @return optimal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OPTIMAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OptimalHoldings getOptimal() {
    return optimal;
  }


  public void setOptimal(OptimalHoldings optimal) {
    this.optimal = optimal;
  }


  public OutputTypes account(OptimalPortfolio account) {
    
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OptimalPortfolio getAccount() {
    return account;
  }


  public void setAccount(OptimalPortfolio account) {
    this.account = account;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputTypes outputTypes = (OutputTypes) o;
    return Objects.equals(this.trades, outputTypes.trades) &&
        Objects.equals(this.optimal, outputTypes.optimal) &&
        Objects.equals(this.account, outputTypes.account);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trades, optimal, account);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputTypes {\n");
    sb.append("    trades: ").append(toIndentedString(trades)).append("\n");
    sb.append("    optimal: ").append(toIndentedString(optimal)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

