/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * PACommentaryDate
 */
@JsonPropertyOrder({
  PACommentaryDate.JSON_PROPERTY_YYYYMMDD,
  PACommentaryDate.JSON_PROPERTY_RELATIVE
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class PACommentaryDate implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_YYYYMMDD = "yyyymmdd";
  private Integer yyyymmdd;

  public static final String JSON_PROPERTY_RELATIVE = "relative";
  private String relative;


  public PACommentaryDate yyyymmdd(Integer yyyymmdd) {
    this.yyyymmdd = yyyymmdd;
    return this;
  }

   /**
   * Date can be either absolute (YYYYMMDD) or relative, but only one format should be set at a time.
   * @return yyyymmdd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date can be either absolute (YYYYMMDD) or relative, but only one format should be set at a time.")
  @JsonProperty(JSON_PROPERTY_YYYYMMDD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getYyyymmdd() {
    return yyyymmdd;
  }


  public void setYyyymmdd(Integer yyyymmdd) {
    this.yyyymmdd = yyyymmdd;
  }


  public PACommentaryDate relative(String relative) {
    this.relative = relative;
    return this;
  }

   /**
   * Date can be either relative or absolute (YYYYMMDD), but only one format should be set at a time.
   * @return relative
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date can be either relative or absolute (YYYYMMDD), but only one format should be set at a time.")
  @JsonProperty(JSON_PROPERTY_RELATIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelative() {
    return relative;
  }


  public void setRelative(String relative) {
    this.relative = relative;
  }


  /**
   * Return true if this PACommentaryDate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PACommentaryDate paCommentaryDate = (PACommentaryDate) o;
    return Objects.equals(this.yyyymmdd, paCommentaryDate.yyyymmdd) &&
        Objects.equals(this.relative, paCommentaryDate.relative);
  }

  @Override
  public int hashCode() {
    return Objects.hash(yyyymmdd, relative);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PACommentaryDate {\n");
    sb.append("    yyyymmdd: ").append(toIndentedString(yyyymmdd)).append("\n");
    sb.append("    relative: ").append(toIndentedString(relative)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

