/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * PACommentaryGetStatus
 */
@JsonPropertyOrder({
  PACommentaryGetStatus.JSON_PROPERTY_CALCULATIONID,
  PACommentaryGetStatus.JSON_PROPERTY_UNITID,
  PACommentaryGetStatus.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class PACommentaryGetStatus implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CALCULATIONID = "calculationid";
  private String calculationid;

  public static final String JSON_PROPERTY_UNITID = "unitid";
  private String unitid;

  /**
   * The status of commentary generation.
   */
  public enum StatusEnum {
    EXECUTING("Executing"),
    
    SUCCESS("Success");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;


  public PACommentaryGetStatus calculationid(String calculationid) {
    this.calculationid = calculationid;
    return this;
  }

   /**
   * Calculation id.
   * @return calculationid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Calculation id.")
  @JsonProperty(JSON_PROPERTY_CALCULATIONID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCalculationid() {
    return calculationid;
  }


  public void setCalculationid(String calculationid) {
    this.calculationid = calculationid;
  }


  public PACommentaryGetStatus unitid(String unitid) {
    this.unitid = unitid;
    return this;
  }

   /**
   * Calculation unit id.
   * @return unitid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Calculation unit id.")
  @JsonProperty(JSON_PROPERTY_UNITID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnitid() {
    return unitid;
  }


  public void setUnitid(String unitid) {
    this.unitid = unitid;
  }


  public PACommentaryGetStatus status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The status of commentary generation.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The status of commentary generation.")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  /**
   * Return true if this PACommentaryGetStatus object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PACommentaryGetStatus paCommentaryGetStatus = (PACommentaryGetStatus) o;
    return Objects.equals(this.calculationid, paCommentaryGetStatus.calculationid) &&
        Objects.equals(this.unitid, paCommentaryGetStatus.unitid) &&
        Objects.equals(this.status, paCommentaryGetStatus.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(calculationid, unitid, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PACommentaryGetStatus {\n");
    sb.append("    calculationid: ").append(toIndentedString(calculationid)).append("\n");
    sb.append("    unitid: ").append(toIndentedString(unitid)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

