/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import factset.analyticsapi.engines.models.Section;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * PACommentary
 */
@JsonPropertyOrder({
  PACommentary.JSON_PROPERTY_COMMENTARY_ID,
  PACommentary.JSON_PROPERTY_SECTIONS,
  PACommentary.JSON_PROPERTY_DISCLAIMER
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class PACommentary implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_COMMENTARY_ID = "commentaryId";
  private String commentaryId;

  public static final String JSON_PROPERTY_SECTIONS = "sections";
  private java.util.List<Section> sections = null;

  public static final String JSON_PROPERTY_DISCLAIMER = "disclaimer";
  private String disclaimer;


  public PACommentary commentaryId(String commentaryId) {
    this.commentaryId = commentaryId;
    return this;
  }

   /**
   * Generated commentary Id
   * @return commentaryId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Generated commentary Id")
  @JsonProperty(JSON_PROPERTY_COMMENTARY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommentaryId() {
    return commentaryId;
  }


  public void setCommentaryId(String commentaryId) {
    this.commentaryId = commentaryId;
  }


  public PACommentary sections(java.util.List<Section> sections) {
    this.sections = sections;
    return this;
  }

  public PACommentary addSectionsItem(Section sectionsItem) {
    if (this.sections == null) {
      this.sections = new java.util.ArrayList<Section>();
    }
    this.sections.add(sectionsItem);
    return this;
  }

   /**
   * Commentary sections
   * @return sections
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Commentary sections")
  @JsonProperty(JSON_PROPERTY_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.List<Section> getSections() {
    return sections;
  }


  public void setSections(java.util.List<Section> sections) {
    this.sections = sections;
  }


  public PACommentary disclaimer(String disclaimer) {
    this.disclaimer = disclaimer;
    return this;
  }

   /**
   * Disclaimer
   * @return disclaimer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disclaimer")
  @JsonProperty(JSON_PROPERTY_DISCLAIMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisclaimer() {
    return disclaimer;
  }


  public void setDisclaimer(String disclaimer) {
    this.disclaimer = disclaimer;
  }


  /**
   * Return true if this PACommentary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PACommentary paCommentary = (PACommentary) o;
    return Objects.equals(this.commentaryId, paCommentary.commentaryId) &&
        Objects.equals(this.sections, paCommentary.sections) &&
        Objects.equals(this.disclaimer, paCommentary.disclaimer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentaryId, sections, disclaimer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PACommentary {\n");
    sb.append("    commentaryId: ").append(toIndentedString(commentaryId)).append("\n");
    sb.append("    sections: ").append(toIndentedString(sections)).append("\n");
    sb.append("    disclaimer: ").append(toIndentedString(disclaimer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

