/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * QuantScreeningExpressionUniverse1
 */
@JsonPropertyOrder({
  QuantScreeningExpressionUniverse1.JSON_PROPERTY_UNIVERSE_EXPR,
  QuantScreeningExpressionUniverse1.JSON_PROPERTY_UNIVERSE_TYPE,
  QuantScreeningExpressionUniverse1.JSON_PROPERTY_SECURITY_EXPR,
  QuantScreeningExpressionUniverse1.JSON_PROPERTY_SOURCE
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class QuantScreeningExpressionUniverse1 implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_UNIVERSE_EXPR = "universeExpr";
  private String universeExpr;

  /**
   * Gets or Sets universeType
   */
  public enum UniverseTypeEnum {
    EQUITY("Equity"),
    
    DEBT("Debt");

    private String value;

    UniverseTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static UniverseTypeEnum fromValue(String value) {
      for (UniverseTypeEnum b : UniverseTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_UNIVERSE_TYPE = "universeType";
  private UniverseTypeEnum universeType;

  public static final String JSON_PROPERTY_SECURITY_EXPR = "securityExpr";
  private String securityExpr;

  /**
   * Gets or Sets source
   */
  public enum SourceEnum {
    SCREENINGEXPRESSIONUNIVERSE("ScreeningExpressionUniverse"),
    
    UNIVERSALSCREENUNIVERSE("UniversalScreenUniverse"),
    
    IDENTIFIERUNIVERSE("IdentifierUniverse");

    private String value;

    SourceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceEnum fromValue(String value) {
      for (SourceEnum b : SourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE = "source";
  private SourceEnum source;


  public QuantScreeningExpressionUniverse1 universeExpr(String universeExpr) {
    this.universeExpr = universeExpr;
    return this;
  }

   /**
   * Get universeExpr
   * @return universeExpr
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UNIVERSE_EXPR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUniverseExpr() {
    return universeExpr;
  }


  @JsonProperty(JSON_PROPERTY_UNIVERSE_EXPR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUniverseExpr(String universeExpr) {
    this.universeExpr = universeExpr;
  }


  public QuantScreeningExpressionUniverse1 universeType(UniverseTypeEnum universeType) {
    this.universeType = universeType;
    return this;
  }

   /**
   * Get universeType
   * @return universeType
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UNIVERSE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UniverseTypeEnum getUniverseType() {
    return universeType;
  }


  @JsonProperty(JSON_PROPERTY_UNIVERSE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUniverseType(UniverseTypeEnum universeType) {
    this.universeType = universeType;
  }


  public QuantScreeningExpressionUniverse1 securityExpr(String securityExpr) {
    this.securityExpr = securityExpr;
    return this;
  }

   /**
   * Get securityExpr
   * @return securityExpr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SECURITY_EXPR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecurityExpr() {
    return securityExpr;
  }


  @JsonProperty(JSON_PROPERTY_SECURITY_EXPR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecurityExpr(String securityExpr) {
    this.securityExpr = securityExpr;
  }


  public QuantScreeningExpressionUniverse1 source(SourceEnum source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SourceEnum getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(SourceEnum source) {
    this.source = source;
  }


  /**
   * Return true if this QuantScreeningExpressionUniverse1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuantScreeningExpressionUniverse1 quantScreeningExpressionUniverse1 = (QuantScreeningExpressionUniverse1) o;
    return Objects.equals(this.universeExpr, quantScreeningExpressionUniverse1.universeExpr) &&
        Objects.equals(this.universeType, quantScreeningExpressionUniverse1.universeType) &&
        Objects.equals(this.securityExpr, quantScreeningExpressionUniverse1.securityExpr) &&
        Objects.equals(this.source, quantScreeningExpressionUniverse1.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(universeExpr, universeType, securityExpr, source);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuantScreeningExpressionUniverse1 {\n");
    sb.append("    universeExpr: ").append(toIndentedString(universeExpr)).append("\n");
    sb.append("    universeType: ").append(toIndentedString(universeType)).append("\n");
    sb.append("    securityExpr: ").append(toIndentedString(securityExpr)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

