/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import factset.analyticsapi.engines.models.QuantDateList;
import factset.analyticsapi.engines.models.QuantFdsDate;
import factset.analyticsapi.engines.models.QuantFqlExpression;
import factset.analyticsapi.engines.models.QuantIdentifierUniverse;
import factset.analyticsapi.engines.models.QuantScreeningExpression;
import factset.analyticsapi.engines.models.QuantScreeningExpressionUniverse;
import factset.analyticsapi.engines.models.QuantUniversalScreenParameter;
import factset.analyticsapi.engines.models.QuantUniversalScreenUniverse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * QuantCalculationParameters
 */
@JsonPropertyOrder({
  QuantCalculationParameters.JSON_PROPERTY_SCREENING_EXPRESSION_UNIVERSE,
  QuantCalculationParameters.JSON_PROPERTY_UNIVERSAL_SCREEN_UNIVERSE,
  QuantCalculationParameters.JSON_PROPERTY_IDENTIFIER_UNIVERSE,
  QuantCalculationParameters.JSON_PROPERTY_FDS_DATE,
  QuantCalculationParameters.JSON_PROPERTY_DATE_LIST,
  QuantCalculationParameters.JSON_PROPERTY_SCREENING_EXPRESSION,
  QuantCalculationParameters.JSON_PROPERTY_FQL_EXPRESSION,
  QuantCalculationParameters.JSON_PROPERTY_UNIVERSAL_SCREEN_PARAMETER,
  QuantCalculationParameters.JSON_PROPERTY_ALL_UNIVERSAL_SCREEN_PARAMETERS
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class QuantCalculationParameters implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SCREENING_EXPRESSION_UNIVERSE = "screeningExpressionUniverse";
  private QuantScreeningExpressionUniverse screeningExpressionUniverse;

  public static final String JSON_PROPERTY_UNIVERSAL_SCREEN_UNIVERSE = "universalScreenUniverse";
  private QuantUniversalScreenUniverse universalScreenUniverse;

  public static final String JSON_PROPERTY_IDENTIFIER_UNIVERSE = "identifierUniverse";
  private QuantIdentifierUniverse identifierUniverse;

  public static final String JSON_PROPERTY_FDS_DATE = "fdsDate";
  private QuantFdsDate fdsDate;

  public static final String JSON_PROPERTY_DATE_LIST = "dateList";
  private QuantDateList dateList;

  public static final String JSON_PROPERTY_SCREENING_EXPRESSION = "screeningExpression";
  private java.util.List<QuantScreeningExpression> screeningExpression = null;

  public static final String JSON_PROPERTY_FQL_EXPRESSION = "fqlExpression";
  private java.util.List<QuantFqlExpression> fqlExpression = null;

  public static final String JSON_PROPERTY_UNIVERSAL_SCREEN_PARAMETER = "universalScreenParameter";
  private java.util.List<QuantUniversalScreenParameter> universalScreenParameter = null;

  public static final String JSON_PROPERTY_ALL_UNIVERSAL_SCREEN_PARAMETERS = "allUniversalScreenParameters";
  private java.util.List<Object> allUniversalScreenParameters = null;


  public QuantCalculationParameters screeningExpressionUniverse(QuantScreeningExpressionUniverse screeningExpressionUniverse) {
    this.screeningExpressionUniverse = screeningExpressionUniverse;
    return this;
  }

   /**
   * Get screeningExpressionUniverse
   * @return screeningExpressionUniverse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCREENING_EXPRESSION_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuantScreeningExpressionUniverse getScreeningExpressionUniverse() {
    return screeningExpressionUniverse;
  }


  @JsonProperty(JSON_PROPERTY_SCREENING_EXPRESSION_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScreeningExpressionUniverse(QuantScreeningExpressionUniverse screeningExpressionUniverse) {
    this.screeningExpressionUniverse = screeningExpressionUniverse;
  }


  public QuantCalculationParameters universalScreenUniverse(QuantUniversalScreenUniverse universalScreenUniverse) {
    this.universalScreenUniverse = universalScreenUniverse;
    return this;
  }

   /**
   * Get universalScreenUniverse
   * @return universalScreenUniverse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNIVERSAL_SCREEN_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuantUniversalScreenUniverse getUniversalScreenUniverse() {
    return universalScreenUniverse;
  }


  @JsonProperty(JSON_PROPERTY_UNIVERSAL_SCREEN_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUniversalScreenUniverse(QuantUniversalScreenUniverse universalScreenUniverse) {
    this.universalScreenUniverse = universalScreenUniverse;
  }


  public QuantCalculationParameters identifierUniverse(QuantIdentifierUniverse identifierUniverse) {
    this.identifierUniverse = identifierUniverse;
    return this;
  }

   /**
   * Get identifierUniverse
   * @return identifierUniverse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_IDENTIFIER_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuantIdentifierUniverse getIdentifierUniverse() {
    return identifierUniverse;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER_UNIVERSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifierUniverse(QuantIdentifierUniverse identifierUniverse) {
    this.identifierUniverse = identifierUniverse;
  }


  public QuantCalculationParameters fdsDate(QuantFdsDate fdsDate) {
    this.fdsDate = fdsDate;
    return this;
  }

   /**
   * Get fdsDate
   * @return fdsDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FDS_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuantFdsDate getFdsDate() {
    return fdsDate;
  }


  @JsonProperty(JSON_PROPERTY_FDS_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFdsDate(QuantFdsDate fdsDate) {
    this.fdsDate = fdsDate;
  }


  public QuantCalculationParameters dateList(QuantDateList dateList) {
    this.dateList = dateList;
    return this;
  }

   /**
   * Get dateList
   * @return dateList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATE_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QuantDateList getDateList() {
    return dateList;
  }


  @JsonProperty(JSON_PROPERTY_DATE_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateList(QuantDateList dateList) {
    this.dateList = dateList;
  }


  public QuantCalculationParameters screeningExpression(java.util.List<QuantScreeningExpression> screeningExpression) {
    this.screeningExpression = screeningExpression;
    return this;
  }

  public QuantCalculationParameters addScreeningExpressionItem(QuantScreeningExpression screeningExpressionItem) {
    if (this.screeningExpression == null) {
      this.screeningExpression = new java.util.ArrayList<QuantScreeningExpression>();
    }
    this.screeningExpression.add(screeningExpressionItem);
    return this;
  }

   /**
   * Get screeningExpression
   * @return screeningExpression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCREENING_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.List<QuantScreeningExpression> getScreeningExpression() {
    return screeningExpression;
  }


  @JsonProperty(JSON_PROPERTY_SCREENING_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScreeningExpression(java.util.List<QuantScreeningExpression> screeningExpression) {
    this.screeningExpression = screeningExpression;
  }


  public QuantCalculationParameters fqlExpression(java.util.List<QuantFqlExpression> fqlExpression) {
    this.fqlExpression = fqlExpression;
    return this;
  }

  public QuantCalculationParameters addFqlExpressionItem(QuantFqlExpression fqlExpressionItem) {
    if (this.fqlExpression == null) {
      this.fqlExpression = new java.util.ArrayList<QuantFqlExpression>();
    }
    this.fqlExpression.add(fqlExpressionItem);
    return this;
  }

   /**
   * Get fqlExpression
   * @return fqlExpression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FQL_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.List<QuantFqlExpression> getFqlExpression() {
    return fqlExpression;
  }


  @JsonProperty(JSON_PROPERTY_FQL_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFqlExpression(java.util.List<QuantFqlExpression> fqlExpression) {
    this.fqlExpression = fqlExpression;
  }


  public QuantCalculationParameters universalScreenParameter(java.util.List<QuantUniversalScreenParameter> universalScreenParameter) {
    this.universalScreenParameter = universalScreenParameter;
    return this;
  }

  public QuantCalculationParameters addUniversalScreenParameterItem(QuantUniversalScreenParameter universalScreenParameterItem) {
    if (this.universalScreenParameter == null) {
      this.universalScreenParameter = new java.util.ArrayList<QuantUniversalScreenParameter>();
    }
    this.universalScreenParameter.add(universalScreenParameterItem);
    return this;
  }

   /**
   * Get universalScreenParameter
   * @return universalScreenParameter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_UNIVERSAL_SCREEN_PARAMETER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.List<QuantUniversalScreenParameter> getUniversalScreenParameter() {
    return universalScreenParameter;
  }


  @JsonProperty(JSON_PROPERTY_UNIVERSAL_SCREEN_PARAMETER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUniversalScreenParameter(java.util.List<QuantUniversalScreenParameter> universalScreenParameter) {
    this.universalScreenParameter = universalScreenParameter;
  }


  public QuantCalculationParameters allUniversalScreenParameters(java.util.List<Object> allUniversalScreenParameters) {
    this.allUniversalScreenParameters = allUniversalScreenParameters;
    return this;
  }

  public QuantCalculationParameters addAllUniversalScreenParametersItem(Object allUniversalScreenParametersItem) {
    if (this.allUniversalScreenParameters == null) {
      this.allUniversalScreenParameters = new java.util.ArrayList<Object>();
    }
    this.allUniversalScreenParameters.add(allUniversalScreenParametersItem);
    return this;
  }

   /**
   * Get allUniversalScreenParameters
   * @return allUniversalScreenParameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALL_UNIVERSAL_SCREEN_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.List<Object> getAllUniversalScreenParameters() {
    return allUniversalScreenParameters;
  }


  @JsonProperty(JSON_PROPERTY_ALL_UNIVERSAL_SCREEN_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllUniversalScreenParameters(java.util.List<Object> allUniversalScreenParameters) {
    this.allUniversalScreenParameters = allUniversalScreenParameters;
  }


  /**
   * Return true if this QuantCalculationParameters object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuantCalculationParameters quantCalculationParameters = (QuantCalculationParameters) o;
    return Objects.equals(this.screeningExpressionUniverse, quantCalculationParameters.screeningExpressionUniverse) &&
        Objects.equals(this.universalScreenUniverse, quantCalculationParameters.universalScreenUniverse) &&
        Objects.equals(this.identifierUniverse, quantCalculationParameters.identifierUniverse) &&
        Objects.equals(this.fdsDate, quantCalculationParameters.fdsDate) &&
        Objects.equals(this.dateList, quantCalculationParameters.dateList) &&
        Objects.equals(this.screeningExpression, quantCalculationParameters.screeningExpression) &&
        Objects.equals(this.fqlExpression, quantCalculationParameters.fqlExpression) &&
        Objects.equals(this.universalScreenParameter, quantCalculationParameters.universalScreenParameter) &&
        Objects.equals(this.allUniversalScreenParameters, quantCalculationParameters.allUniversalScreenParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(screeningExpressionUniverse, universalScreenUniverse, identifierUniverse, fdsDate, dateList, screeningExpression, fqlExpression, universalScreenParameter, allUniversalScreenParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuantCalculationParameters {\n");
    sb.append("    screeningExpressionUniverse: ").append(toIndentedString(screeningExpressionUniverse)).append("\n");
    sb.append("    universalScreenUniverse: ").append(toIndentedString(universalScreenUniverse)).append("\n");
    sb.append("    identifierUniverse: ").append(toIndentedString(identifierUniverse)).append("\n");
    sb.append("    fdsDate: ").append(toIndentedString(fdsDate)).append("\n");
    sb.append("    dateList: ").append(toIndentedString(dateList)).append("\n");
    sb.append("    screeningExpression: ").append(toIndentedString(screeningExpression)).append("\n");
    sb.append("    fqlExpression: ").append(toIndentedString(fqlExpression)).append("\n");
    sb.append("    universalScreenParameter: ").append(toIndentedString(universalScreenParameter)).append("\n");
    sb.append("    allUniversalScreenParameters: ").append(toIndentedString(allUniversalScreenParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

