/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,spar,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,others],v1:[fiab]
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * QuantDateListAllOf
 */
@JsonPropertyOrder({
  QuantDateListAllOf.JSON_PROPERTY_DATES
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class QuantDateListAllOf implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DATES = "dates";
  private JsonNullable<java.util.List<String>> dates = JsonNullable.<java.util.List<String>>undefined();


  public QuantDateListAllOf dates(java.util.List<String> dates) {
    this.dates = JsonNullable.<java.util.List<String>>of(dates);
    return this;
  }

  public QuantDateListAllOf addDatesItem(String datesItem) {
    if (this.dates == null || !this.dates.isPresent()) {
      this.dates = JsonNullable.<java.util.List<String>>of(new java.util.ArrayList<String>());
    }
    try {
      this.dates.get().add(datesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public java.util.List<String> getDates() {
        return dates.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<java.util.List<String>> getDates_JsonNullable() {
    return dates;
  }
  
  @JsonProperty(JSON_PROPERTY_DATES)
  public void setDates_JsonNullable(JsonNullable<java.util.List<String>> dates) {
    this.dates = dates;
  }

  public void setDates(java.util.List<String> dates) {
    this.dates = JsonNullable.<java.util.List<String>>of(dates);
  }


  /**
   * Return true if this QuantDateList_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuantDateListAllOf quantDateListAllOf = (QuantDateListAllOf) o;
    return Objects.equals(this.dates, quantDateListAllOf.dates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuantDateListAllOf {\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

