/*
 * Engines API
 * Allow clients to fetch Analytics through APIs.
 *
 * The version of the OpenAPI document: v3:[pa,vault,pub,quant,fi,axp,afi,npo,bpm,fpo,security-modeling,others],v1:[fiab]
 * Contact: api@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import factset.analyticsapi.engines.models.OneOfFieldsFields;
import factset.analyticsapi.engines.models.SMError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import factset.analyticsapi.engines.JSON;


/**
 * SMRetrieveResponse
 */
@JsonPropertyOrder({
  SMRetrieveResponse.JSON_PROPERTY_SECURITY_NAME,
  SMRetrieveResponse.JSON_PROPERTY_STATUS,
  SMRetrieveResponse.JSON_PROPERTY_LOCATION,
  SMRetrieveResponse.JSON_PROPERTY_ASOFDATE,
  SMRetrieveResponse.JSON_PROPERTY_FIELDS,
  SMRetrieveResponse.JSON_PROPERTY_ERRORS
})
@javax.annotation.Generated(value = "CustomJavaClientCodegen")
public class SMRetrieveResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SECURITY_NAME = "securityName";
  private String securityName;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    SUCCESS("success"),
    
    FAILURE("failure");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_LOCATION = "location";
  private String location;

  public static final String JSON_PROPERTY_ASOFDATE = "asofdate";
  private String asofdate;

  public static final String JSON_PROPERTY_FIELDS = "fields";
  private OneOfFieldsFields fields = null;

  public static final String JSON_PROPERTY_ERRORS = "errors";
  private java.util.List<SMError> errors = null;


  public SMRetrieveResponse securityName(String securityName) {
    this.securityName = securityName;
    return this;
  }

   /**
   * Get securityName
   * @return securityName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SECURITY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecurityName() {
    return securityName;
  }


  public void setSecurityName(String securityName) {
    this.securityName = securityName;
  }


  public SMRetrieveResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public SMRetrieveResponse location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  public SMRetrieveResponse asofdate(String asofdate) {
    this.asofdate = asofdate;
    return this;
  }

   /**
   * Get asofdate
   * @return asofdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ASOFDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAsofdate() {
    return asofdate;
  }


  public void setAsofdate(String asofdate) {
    this.asofdate = asofdate;
  }


  public SMRetrieveResponse fields(OneOfFieldsFields fields) {
    this.fields = fields;
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OneOfFieldsFields getFields() {
    return fields;
  }


  public void setFields(OneOfFieldsFields fields) {
    this.fields = fields;
  }


  public SMRetrieveResponse errors(java.util.List<SMError> errors) {
    this.errors = errors;
    return this;
  }

  public SMRetrieveResponse addErrorsItem(SMError errorsItem) {
    if (this.errors == null) {
      this.errors = new java.util.ArrayList<SMError>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.List<SMError> getErrors() {
    return errors;
  }


  public void setErrors(java.util.List<SMError> errors) {
    this.errors = errors;
  }


  /**
   * Return true if this SMRetrieveResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SMRetrieveResponse smRetrieveResponse = (SMRetrieveResponse) o;
    return Objects.equals(this.securityName, smRetrieveResponse.securityName) &&
        Objects.equals(this.status, smRetrieveResponse.status) &&
        Objects.equals(this.location, smRetrieveResponse.location) &&
        Objects.equals(this.asofdate, smRetrieveResponse.asofdate) &&
        Objects.equals(this.fields, smRetrieveResponse.fields) &&
        Objects.equals(this.errors, smRetrieveResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(securityName, status, location, asofdate, fields, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SMRetrieveResponse {\n");
    sb.append("    securityName: ").append(toIndentedString(securityName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    asofdate: ").append(toIndentedString(asofdate)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

