/*
 * Engines API
 * Allow clients to fetch Engines Analytics through APIs.
 *
 * The version of the OpenAPI document: 2
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import factset.analyticsapi.engines.v2.models.PACalculationParameters;
import factset.analyticsapi.engines.v2.models.SPARCalculationParameters;
import factset.analyticsapi.engines.v2.models.VaultCalculationParameters;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Calculation
 */

public class Calculation implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PA = "pa";
  private java.util.Map<String, PACalculationParameters> pa = null;

  public static final String JSON_PROPERTY_SPAR = "spar";
  private java.util.Map<String, SPARCalculationParameters> spar = null;

  public static final String JSON_PROPERTY_VAULT = "vault";
  private java.util.Map<String, VaultCalculationParameters> vault = null;


  public Calculation pa(java.util.Map<String, PACalculationParameters> pa) {
    
    this.pa = pa;
    return this;
  }

  public Calculation putPaItem(String key, PACalculationParameters paItem) {
    if (this.pa == null) {
      this.pa = new java.util.HashMap<String, PACalculationParameters>();
    }
    this.pa.put(key, paItem);
    return this;
  }

   /**
   * Get pa
   * @return pa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.Map<String, PACalculationParameters> getPa() {
    return pa;
  }



  public void setPa(java.util.Map<String, PACalculationParameters> pa) {
    this.pa = pa;
  }


  public Calculation spar(java.util.Map<String, SPARCalculationParameters> spar) {
    
    this.spar = spar;
    return this;
  }

  public Calculation putSparItem(String key, SPARCalculationParameters sparItem) {
    if (this.spar == null) {
      this.spar = new java.util.HashMap<String, SPARCalculationParameters>();
    }
    this.spar.put(key, sparItem);
    return this;
  }

   /**
   * Get spar
   * @return spar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SPAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.Map<String, SPARCalculationParameters> getSpar() {
    return spar;
  }



  public void setSpar(java.util.Map<String, SPARCalculationParameters> spar) {
    this.spar = spar;
  }


  public Calculation vault(java.util.Map<String, VaultCalculationParameters> vault) {
    
    this.vault = vault;
    return this;
  }

  public Calculation putVaultItem(String key, VaultCalculationParameters vaultItem) {
    if (this.vault == null) {
      this.vault = new java.util.HashMap<String, VaultCalculationParameters>();
    }
    this.vault.put(key, vaultItem);
    return this;
  }

   /**
   * Get vault
   * @return vault
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VAULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.util.Map<String, VaultCalculationParameters> getVault() {
    return vault;
  }



  public void setVault(java.util.Map<String, VaultCalculationParameters> vault) {
    this.vault = vault;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Calculation calculation = (Calculation) o;
    return Objects.equals(this.pa, calculation.pa) &&
        Objects.equals(this.spar, calculation.spar) &&
        Objects.equals(this.vault, calculation.vault);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pa, spar, vault);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Calculation {\n");
    sb.append("    pa: ").append(toIndentedString(pa)).append("\n");
    sb.append("    spar: ").append(toIndentedString(spar)).append("\n");
    sb.append("    vault: ").append(toIndentedString(vault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

