/*
 * Engines API
 * Allow clients to fetch Engines Analytics through APIs.
 *
 * The version of the OpenAPI document: 2
 * Contact: analytics.api.support@factset.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package factset.analyticsapi.engines.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * CalculationStatusSummary
 */
@JsonPropertyOrder({
  CalculationStatusSummary.JSON_PROPERTY_STATUS,
  CalculationStatusSummary.JSON_PROPERTY_POINTS,
  CalculationStatusSummary.JSON_PROPERTY_REQUEST_TIME,
  CalculationStatusSummary.JSON_PROPERTY_LAST_POLL_TIME
})

public class CalculationStatusSummary implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    QUEUED("Queued"),
    
    EXECUTING("Executing"),
    
    COMPLETED("Completed"),
    
    CANCELLED("Cancelled");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_POINTS = "points";
  private Integer points;

  public static final String JSON_PROPERTY_REQUEST_TIME = "requestTime";
  private OffsetDateTime requestTime;

  public static final String JSON_PROPERTY_LAST_POLL_TIME = "lastPollTime";
  private OffsetDateTime lastPollTime;


  public CalculationStatusSummary status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public CalculationStatusSummary points(Integer points) {
    
    this.points = points;
    return this;
  }

   /**
   * Number of calculation units in batch.
   * @return points
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of calculation units in batch.")
  @JsonProperty(JSON_PROPERTY_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPoints() {
    return points;
  }


  public void setPoints(Integer points) {
    this.points = points;
  }


  public CalculationStatusSummary requestTime(OffsetDateTime requestTime) {
    
    this.requestTime = requestTime;
    return this;
  }

   /**
   * Request time of calculation.
   * @return requestTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Request time of calculation.")
  @JsonProperty(JSON_PROPERTY_REQUEST_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRequestTime() {
    return requestTime;
  }


  public void setRequestTime(OffsetDateTime requestTime) {
    this.requestTime = requestTime;
  }


  public CalculationStatusSummary lastPollTime(OffsetDateTime lastPollTime) {
    
    this.lastPollTime = lastPollTime;
    return this;
  }

   /**
   * Last poll time of calculation.
   * @return lastPollTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Last poll time of calculation.")
  @JsonProperty(JSON_PROPERTY_LAST_POLL_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastPollTime() {
    return lastPollTime;
  }


  public void setLastPollTime(OffsetDateTime lastPollTime) {
    this.lastPollTime = lastPollTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalculationStatusSummary calculationStatusSummary = (CalculationStatusSummary) o;
    return Objects.equals(this.status, calculationStatusSummary.status) &&
        Objects.equals(this.points, calculationStatusSummary.points) &&
        Objects.equals(this.requestTime, calculationStatusSummary.requestTime) &&
        Objects.equals(this.lastPollTime, calculationStatusSummary.lastPollTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, points, requestTime, lastPollTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalculationStatusSummary {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    requestTime: ").append(toIndentedString(requestTime)).append("\n");
    sb.append("    lastPollTime: ").append(toIndentedString(lastPollTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

